repos:
    # Various general + format-specific helpers
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.6.0
      hooks:
          - id: check-yaml
          - id: end-of-file-fixer
          - id: trailing-whitespace
    - repo: https://github.com/python-jsonschema/check-jsonschema
      rev: '0.33.0'
      hooks:
          - id: check-github-workflows
            exclude: ^spotizerr-ui/
    - repo: https://github.com/astral-sh/ruff-pre-commit
      # Ruff version.
      rev: v0.11.13
      hooks:
          # Run the linter.
          - id: ruff
            types_or: [python, pyi, jupyter]
            args: [--fix]
            exclude: ^spotizerr-ui/
          # Run the formatter.
          - id: ruff-format
            types_or: [python, pyi, jupyter]
            exclude: ^spotizerr-ui/
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: 'v1.16.0'
      hooks:
          - id: mypy
            args: [--no-strict-optional, --ignore-missing-imports]
            exclude: ^spotizerr-ui/
            # NOTE: you might need to add some deps here:
            additional_dependencies: [waitress==3.0.2, types-waitress, types-requests]
    - repo: local
      hooks:
        - id: ensure-compose-image
          name: Ensure docker-compose image is cooldockerizer93/spotizerr
          entry: python3 .github/scripts/ensure_compose_image.py docker-compose.yaml
          language: system
          files: ^docker-compose\.ya?ml$
