name: spotizerr

services:
  spotizerr:
    image: cooldockerizer93/spotizerr:ee
    volumes:
      - ./data:/app/data
      - ./downloads:/app/downloads  # <-- Change this for your music library dir
      - ./logs:/app/logs  # <-- Volume for persistent logs
    ports:
      - 7171:7171
    container_name: spotizerr-app
    restart: unless-stopped
    env_file:
      - .env

    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: spotizerr-redis
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - redis-data:/data
    command: sh -c 'redis-server --requirepass "$REDIS_PASSWORD" --appendonly yes'

volumes:
  redis-data:
    driver: local
