name: spotizerr
services:
  spotizerr:
    image: cooldockerizer93/spotizerr:beta
    volumes:
    - ./data:/app/data
    - ./downloads:/app/downloads
    - ./logs:/app/logs
    ports:
    - 7171:7171
    container_name: spotizerr-app
    user: "1000:1000" # spotizerr user:group ids
    restart: unless-stopped
    env_file:
    - .env
    depends_on:
    - redis
  redis:
    image: redis:alpine
    container_name: spotizerr-redis
    restart: unless-stopped
    env_file:
    - .env
    volumes:
    - redis-data:/data
    command: sh -c 'redis-server --requirepass "$REDIS_PASSWORD" --appendonly yes'
volumes:
  redis-data:
    driver: local
