name: spotizerr

services:
  spotizerr:
    image: cooldockerizer93/spotizerr:beta
    volumes:
      - ./data:/app/data
      - ./downloads:/app/downloads  # <-- Change this for your music library dir
      - ./logs:/app/logs  # <-- Volume for persistent logs
    ports:
      - 7171:7171
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spotizerr-app
    restart: unless-stopped
    environment:
      - PUID=${PUID}  # Replace with your desired user ID  | Remove both if you want to run as root (not recommended, might result in unreadable files)
      - PGID=${PGID}  # Replace with your desired group ID | The user must have write permissions in the volume mapped to /app/downloads
      - UMASK=${UMASK} # Optional: Sets the default file permissions for newly created files within the container.
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}
      - REDIS_PASSWORD=${REDIS_PASSWORD}  # Optional, Redis AUTH password. Leave empty if not using authentication
      - REDIS_URL=redis://:${REDIS_PASSWORD}@${REDIS_HOST}:${REDIS_PORT}/${REDIS_DB}
      - REDIS_BACKEND=redis://:${REDIS_PASSWORD}@${REDIS_HOST}:${REDIS_PORT}/${REDIS_DB}
      - EXPLICIT_FILTER=${EXPLICIT_FILTER} # Set to true to filter out explicit content
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: spotizerr-redis
    restart: unless-stopped
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - redis-data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes

volumes:
  redis-data:
    driver: local
